name: x86-windows

on:
  workflow_dispatch:
  push:
    branches: [ "master", "dev" ]

env:
  BUILD_TYPE: Release
  BUILD_DIR: build-windows
  BUILD_OUT: build-out

jobs:
  skip_check:
    continue-on-error: false
    runs-on: ubuntu-22.04
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
    - id: skip_check
      uses: fkirc/skip-duplicate-actions@v5
      with:
        concurrent_skipping: 'same_content'
        cancel_others: 'true'
        skip_after_successful_duplicate: 'true'
        paths_ignore: '["**/README.md", "**/docs/**", "**/LICENSE.txt"]'
        do_not_skip: '["workflow_dispatch", "schedule"]'

  build:
    needs: skip_check
    if: needs.skip_check.outputs.should_skip != 'true'

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Setup vcpkg with caching
      uses: friendlyanon/setup-vcpkg@v1
      with: 
        committish: c9140a3b500812ad3206317885860d9553b93f13
        path: vcpkg

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE:STRING=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -G "Ninja"

    - name: Build
      run: cmake --build ${{github.workspace}}/${{env.BUILD_DIR}} --config ${{env.BUILD_TYPE}}

    - name: Create package
      shell: bash
      run: |
        mkdir -p ${{env.BUILD_OUT}}
        cp ${{env.BUILD_DIR}}/*.exe ${{env.BUILD_OUT}}/
        cp ${{env.BUILD_DIR}}/*.dll ${{env.BUILD_OUT}}/
        cp README.md ${{env.BUILD_OUT}}/

    - name: Upload files (Release)
      uses: actions/upload-artifact@v3
      with:
        name: gps_correlation_windows_x64
        path: ${{github.workspace}}/${{env.BUILD_OUT}}
